### ISSUE TITLE
description disappears in some cases

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-docs#39] opened 2022-01-24 11:32 UTC
In Max, for instance bufchroma, the description text is disapearing. The YAML has it but not the end reference.

**Comment by weefuzzy** [comment] 2022-01-24 11:52
If I do `MAKE_MAX_REF` on `dev` and look at the result, everything seems present in the fluid.bufchroma~ reference with respect to the YAML. 

What branch are you on, and what's missing specifically?

**Comment by tremblap** [comment] 2022-01-24 11:57
I'm looking at the result of tip of the nightlies. The hash has fe9eee0.

Interestingly, it has failed to produce nightlies despite me pushing a single character change...

**Comment by weefuzzy** [comment] 2022-01-24 12:11
I've re-triggered the workflow, it looks like it failed due to some github error (couldn't find the action that does the packaging). 

Meanwhile, can you send me the faulty `fluid.bufchroma~.maxref` from the old nightly so I can see what's actually missing?

**Comment by tremblap** [comment] 2022-01-24 12:12
here we go.

[fluid.bufchroma~.maxref.xml.zip](https://github.com/flucoma/flucoma-docs/files/7925410/fluid.bufchroma.maxref.xml.zip)

**Comment by weefuzzy** [comment] 2022-01-24 12:33
I can see the description for the object missing. However, other things aren't there (the generated warning for `maxnumchroma`) which makes me think this run (from 6 days ago) actually built against the pre-merged state of `dev` on this repo. 

I think this would happen if the workflow was *rerun* and the original run happened before 939e1750fce621f96b0fc14ad8205e9990a9f349 because reruns will always [reuse the git refs from the original run](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs). 

Oh workflow wise-one, @jamesb93, does this seem like a likely explanation? 

Anyway, hopefully the `flucoma-max` run currently going will succeed and you'll see the correct thing

**Comment by weefuzzy** [comment] 2022-01-24 12:51
Ok, new nightly has worked. Docs still look like they're running against older version. @jamesb93 are we positive the workflow is checking out `dev` properly rather than `main`. What's a sensible way to check?

**Comment by tremblap** [comment] 2022-01-24 12:59
the version tag has hash of core and cce but probably not of doc, right?

**Comment by weefuzzy** [comment] 2022-01-24 13:13
Reading the action logs, I think I see what the problem is. Will file an issue in the relevant spot...

**Comment by jamesb93** [comment] 2022-01-24 13:32
Definitely seems likely. I'm not acquainted with the edges of how actions work in many ways it seems.

Docs should be pulling from dev:

https://github.com/flucoma/actions/blob/main/maxdocs/action.yaml

I will add a little post in all the docs actions so we can trace these sorts of things and verify which hash docs gets used.

**Comment by weefuzzy** [comment] 2022-01-24 13:38
See my issue above – it is pulling from dev, but then it also pulls from main and uses that 😄

**Comment by jamesb93** [comment] 2022-01-24 13:40
Apologies I was looking on email and it didn't show your issue in an obvious way :P you're issue is right and an easy fix.

**Comment by jamesb93** [comment] 2022-01-24 18:26
Solved in https://github.com/flucoma/actions/pull/2 while actually propagates everywhere, woo.

**Closed by jamesb93** 2022-01-24 18:26 UTC
